### ISSUE TITLE
Routing destroy functions in panel

### ISSUE THREAD

**Issue by Anjade** [d4l-data4life/kirby3-static-site-generator#68] opened 2022-11-01 17:47 UTC
` 'ready' => function ($kirby) {
      
      $lang = $kirby->language();
      
      $notePerPage = 2; // change later!
      $pagesCount = page('notes')->children()->listed()->count();
      
      $pageNumbers = intval($pagesCount/$notePerPage);
      if (($pagesCount % $notePerPage) != 0)
      {
        $pageNumbers++;
      }
            
      for ($i = 2; $i <= $pageNumbers; $i++)
      {
        $myRoutes[] = [
          'path' => "$lang/notes/$i",
          'route' => "notes/page:$i",
        ];
      }

      return [
          'd4l.static_site_generator.custom_routes' => $myRoutes
      ];
  }`

-------

When i use this, it destroys some functions in the panel and on the dynamic page.

**Comment by jonathan-reisdorf** [comment] 2022-11-11 14:00
Duplicate of https://github.com/d4l-data4life/kirby3-static-site-generator/issues/64
Also I do not understand the issue, but it seems like you have already proceeded with your solution

**Closed as completed by jonathan-reisdorf** 2022-11-11 14:00 UTC
