### ISSUE TITLE
Examples, please

### ISSUE THREAD

**Issue by Anjade** [d4l-data4life/kirby3-static-site-generator#69] opened 2022-11-09 16:03 UTC
Please provide two examples for tag and page with two languages.
Everything should be clear with these examples.

For example i have now idea why i need ready to pass the custom_routes.
Why i cant define them in the config like written in the docs?

Also i can do now
blog/page:[number],

but i fail with
blog/tag:{tag}

i got an error, that these array-key has no value?

the plugin should be work for
blog/page:2 => blog/2 (does)

and also for
blog/tag:dog => blog/dog

Why one works and the other one not?
"page" needs a number

and "tag" an array? An array of what?

**Comment by jonathan-reisdorf** [comment] 2022-11-11 13:58
Duplicate of https://github.com/d4l-data4life/kirby3-static-site-generator/issues/64

I will document examples for your use case once your issue is resolved and the solution is confirmed working.
Until then I recommend to have a look into the Kirby documentation, things are described there much better than I could. E.g. https://getkirby.com/docs/reference/system/options/ready

You have to use `ready` here because the moment where the configuration is parsed, Kirby is not fully initialized yet, so you can not yet do things like getting page objects and generating dynamic configuration based on that.

**Closed as completed by jonathan-reisdorf** 2022-11-11 13:58 UTC
