### ISSUE TITLE
A hint how to care for correct links?

### ISSUE THREAD

**Issue by Anjade** [d4l-data4life/kirby3-static-site-generator#66] opened 2022-10-29 15:11 UTC
I dont have a bug, but a wish.
Are there any ideas, how to handle pagination and links to tag-page, please?
With the help of the author i have builded now all blog-pages and tag-pages, thank you very much for that.

Now i have problem with the links to the tag-pages (still  /.../tag:tagname instead of  /.../tag/tagname) and links in the pagination of the blog: 

/api/generate-static-site
/api/generate-static-site/page:2

Maybe i still have no perfect config?

If so. Are there any strategies how to handle the links, please?

Maybe?

**1**. The link is done with some php like:
is this a static page build by the addon, then link to /.../tag/tagname,
is this a normal kirby page, then link to /.../tag:tagname

is this a static page build by the addon, then link to /.../notes/n
is this a normal kirby page, then link to /.../notes/page:n,

**2**. We change the links before we build the static pages?
I dont have an idea, how to do that.

**3.** Better way?

I guess, it would be very helpful to give a hint how to care for correct links.

**Comment by jonathan-reisdorf** [comment] 2022-11-11 14:01
Duplicate of https://github.com/d4l-data4life/kirby3-static-site-generator/issues/64

**Closed as completed by jonathan-reisdorf** 2022-11-11 14:01 UTC
