### ISSUE TITLE
Plugin generates wrong URL paths and HTML tags when baseUrl is set

### ISSUE THREAD

**Issue by dgsiegel** [d4l-data4life/kirby3-static-site-generator#42] opened 2021-07-19 12:06 UTC
I am using this plugin via a separate PHP file like this:

```
<?php
  require('./index.php');
  $kirby = kirby();
  $staticSiteGenerator = new D4L\StaticSiteGenerator($kirby);
  $list = $staticSiteGenerator->generate($outputFolder = './foobar', $baseUrl = '/foobar/', $preserve = []);
  echo json_encode($list, JSON_PRETTY_PRINT);
```

All pages are exported correctly, however all paths in the HTML files have the word "foobar" in them, e.g.

`<meta property="og:image" content="/foobar/assets/foobar/img/foobar/opengraph.png">`

`<img class="img-fluid" src="/foobar/media/foobar/pages/foobar/hosts/foobar/daniel-burka/foobar/84a8cc761f-1626254128/foobar/1516277198735-768x768.jpg" alt="Some Alt Description">`

Furthermore a few HTML tags have been changed, e.g.

`<title>Page Title</foobar/title>`

`</foobar/div>`

It seems that this `str_replace` (https://github.com/d4l-data4life/kirby3-static-site-generator/blob/master/class.php#L96) might be the culprit as all `/` seem to have been replaced.

## Expected Behavior

Paths should not be changed, except the `base_url` parameter
HTML Tags should stay as they are

## Current Behavior

The plugin currently generates broken HTML and wrong paths.

## Steps to Reproduce

- Execute the PHP script above

## Context

- Kirby 3.5.7.1
- Kirby Builder 2.0.16
- Meta Tags 2.1.0
- Static Site Generator 1.1.1
- PHP 7.4.21

**Comment by dgsiegel** [comment] 2021-07-22 22:30
Did some further testing. The main problem is that the plugin looks for Kirby's base url, without checking if that url actually exists:

https://github.com/d4l-data4life/kirby3-static-site-generator/blob/master/class.php#L39

As this results in an empty string, `str_replace` will then replace `/` with the baseUrl set as a parameter.

According to the docs, Kirby's base url does not have to be set, as it "auto-detects the correct URL":

https://getkirby.com/docs/reference/system/options/url

**Comment by jonathan-reisdorf** [comment] 2021-08-09 09:26
Hi @dgsiegel, thank you for reporting this! I was not aware that it's an option to leave the base url empty. In this case I'll have to temporarily set it in the plugin to have a placeholder/marker in the html the plugin can then replace.

I'll create a PR for the fix later today.

**Comment by jonathan-reisdorf** [comment] 2021-08-09 13:15
The PR is now ready: https://github.com/d4l-data4life/kirby3-static-site-generator/pull/43

@dgsiegel could you please test if the changes from the PR fix the issue for you? Thanks!

**Comment by dgsiegel** [comment] 2021-08-09 15:37
Hey @jonathan-reisdorf, 

thanks for the PR. It works and generates valid HTML, but does not fix the issue.

For example, Kirby generates this line on the server:

`    <meta property="og:image" content="https://example.com/assets/img/opengraph.png">`

However, generating a static site locally with the above PHP script gives me this:

`    <meta property="og:image" content="/assets/img/opengraph.png">`

The base URL is set like this: `$baseUrl = '/foobar/'`. And so I would expect this output:

`    <meta property="og:image" content="/foobar/assets/img/opengraph.png">`

**Comment by jonathan-reisdorf** [comment] 2021-08-10 05:53
Thanks @dgsiegel,

as for your example: Yes, this should work, and I just verified that it does in my test environment. It depends, though, how you generate that url. Can you please post the PHP code you use to produce that meta tag? That would help me reproduce your issue. Also, do you see the `/foobar/` base url in other parts of the rendered page's code? Thanks!

**Comment by dgsiegel** [comment] 2021-08-10 10:30
The meta tags are actually generated with https://getkirby.com/plugins/pedroborges/meta-tags. But looking at other links and images I use lines like these:

```
<img src="<?= url('assets/img/logo.svg') ?>" alt="<?= $site->title() ?>">

<?php foreach ($site->children()->listed() as $key => $item): ?>
  <a href="<?= $item->url() ?>"><?= $item->title()->escape() ?></a>
<?php endforeach ?>

<img src="<?= $image->thumb('square')->url() ?>" srcset="<?= $image->srcset('square') ?>" sizes="(min-width: 768px) 25vw, 50vw" alt="<?= $image->alt()->or($page->title())->escape() ?>">
```

Please note that on a local system Kirby transforms all of these URLs to their absolute form, ie. the first example will be

`<img src="http://localhost:8080/assets/img/logo.svg" alt="Site title">`

locally and on the server:

`<img src="https://example.com/assets/img/logo.svg" alt="Site title">`

The only places where `/foobar/` actually appears is in a place where I programmatically create a fake page in order to include a builder block snippet:

```
    <?php
    $data = Page::factory(['slug' => 'tickets', 'content' => array('spacing' => '6')]);
    snippet("blocks/cta", [ "data" => $data ]);
    ?>
```

and in the meta-tags configuration for `og:url`, where I use this (but only in children pages and not on the main index.html):

```
      'og' => [
        'title' => $page->isHomePage()
          ? $site->title()
          : $page->title() . " - " . $site->title(),
        'description' => $site->description(),
        'url' => $page->url(),
        'type' => 'website',
        'site_name' => $site->title(),
      ],
```

**Comment by jonathan-reisdorf** [comment] 2021-08-10 11:14
Thanks, apparently there is also an index url which plays a big role when generating these urls. On systems where the base url is detected, the index url equals the base url. I have adapted the PR accordingly. Please re-test, thanks!

**Comment by dgsiegel** [comment] 2021-08-10 12:34
It does seem to work for more links now, but not all and definitely not for image urls. I can't really see any rules or fixed behaviours here unfortunately...

I am wondering if it wouldn't be easier to set the base url manually in the PHP script above before calling the static site generator?

**Comment by jonathan-reisdorf** [comment] 2021-08-10 12:57
> I am wondering if it wouldn't be easier to set the base url manually in the PHP script above before calling the static site generator?

@dgsiegel that would certainly work in your case (has to be passed when initializing kirby). It would not fix the generator issue, though, if there is any left.
If as you said there are more urls without the prefix, my assumption is that there are more Kirby urls to be taken into account that need to be converted. Either that or you are not using Kirby functions when generating the urls. I'll have a look once I have more time later today.

**Comment by jonathan-reisdorf** [comment] 2021-08-10 13:56
PR has been updated again. There were more kirby urls which had to be changed. Now all of them are adapted unless they were absolute, which fixes the generation for all your urls. If after this change you still see URLs without the base path, they were hard-coded.

**Comment by jonathan-reisdorf** [comment] 2021-08-10 13:59
Issue has been fixed. Feel free to reopen if anything is still wrong with the url generation.

**Comment by dgsiegel** [comment] 2021-08-10 17:09
I am afraid, I have to reopen this issue as your patch only works partially.

To ensure the issues are not specific to my project, I've used the Kirby Starterkit with the only change of adding static-site-generator as plugin and the above PHP snippet.

As you can see in the generated _Home_ page, links in the header and footer were converted nicely, but not the ones in the content part of the page: [starterkit-home.html.txt](https://github.com/d4l-data4life/kirby3-static-site-generator/files/6963225/starterkit-home.html.txt)

Here's the whole starterkit setup: [starterkit.zip](https://github.com/d4l-data4life/kirby3-static-site-generator/files/6963264/starterkit.zip)

Again, setting `url` in `config.php` completely resolves this issue.

> that would certainly work in your case (has to be passed when initializing kirby).

How would I have to pass it when initializing kirby?

**Comment by jonathan-reisdorf** [comment] 2021-08-16 14:58
@dgsiegel thank you for bringing this up, I have a fix ready which I'll commit in a minute

**Comment by jonathan-reisdorf** [comment] 2021-08-16 15:03
As for your question: There are multiple options to pass the base url (in `index.php` when instantiating Kirby with options, or from the config folder). But now the issue is fixed in the plugin.

**Closed as completed** 2021-08-16 15:03 UTC

**Comment by dgsiegel** [comment] 2021-08-16 15:32
Thanks @jonathan-reisdorf, I've just tested this and can confirm it works as expected.
