### ISSUE TITLE
$pagination->

### ISSUE THREAD

**Issue by Anjade** [d4l-data4life/kirby3-static-site-generator#70] opened 2022-11-11 04:26 UTC
$pagination->nextPageUrl()
$pagination->prevPageUrl()
$pagination->page()

seems not to be translated in the correct link.
Instead i have something like:

https://hundehilfe-pattaya.com/api/generate-static-site/page:2

All pages are builded correct, but it fails to translate the links.

What can i do here, please?

Should $pagaination be replaced by default?
Do i need to do something for me own?

**Comment by Anjade** [comment] 2022-11-11 04:31
Also it seems that the class cares for _page_, but not for _tag_

`    $path = A::get($route, 'path');
    $page = A::get($route, 'page');
    $routePath = A::get($route, 'route');
    $baseUrl = A::get($route, 'baseUrl', $baseUrl);
    $data = A::get($route, 'data', []);
    $languageCode = A::get($route, 'languageCode');

    if (is_string($page)) {
      $page = page($page);
    }

    $routeContent = $page ? null : $this->_getRouteContent($routePath ?: $path);`

**Comment by jonathan-reisdorf** [comment] 2022-11-11 13:55
Duplicate of https://github.com/d4l-data4life/kirby3-static-site-generator/issues/64
I have reopened the ticket since you still have issues. Please explain there with a new comment what your current status with this issue is, including the context.
Please also refrain from opening new issues for the same problem. That makes it easier for other users to distinguish the actual issues from one another. Thanks!

**Closed as completed by jonathan-reisdorf** 2022-11-11 13:55 UTC
